//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTF_STFM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTF_STFM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap appbar_checkmark_cross {
            get {
                object obj = ResourceManager.GetObject("appbar_checkmark_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap appbar_network {
            get {
                object obj = ResourceManager.GetObject("appbar_network", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap appbar_network_home {
            get {
                object obj = ResourceManager.GetObject("appbar_network_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap appbar_network_home_disconnect {
            get {
                object obj = ResourceManager.GetObject("appbar_network_home_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.4.
        /// </summary>
        public static string appVer {
            get {
                return ResourceManager.GetString("appVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- END --.
        /// </summary>
        public static string StringEndMark {
            get {
                return ResourceManager.GetString("StringEndMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効でない日付形式です。.
        /// </summary>
        public static string StringErrLandingDate {
            get {
                return ResourceManager.GetString("StringErrLandingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOODS DETAILS.
        /// </summary>
        public static string StringGoodsDetails {
            get {
                return ResourceManager.GetString("StringGoodsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 購入年月日.
        /// </summary>
        public static string StringGoodsDetails01 {
            get {
                return ResourceManager.GetString("StringGoodsDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消耗品.
        /// </summary>
        public static string StringGoodsDetails02 {
            get {
                return ResourceManager.GetString("StringGoodsDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般物品.
        /// </summary>
        public static string StringGoodsDetails03 {
            get {
                return ResourceManager.GetString("StringGoodsDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名.
        /// </summary>
        public static string StringGoodsDetails04 {
            get {
                return ResourceManager.GetString("StringGoodsDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単価.
        /// </summary>
        public static string StringGoodsDetails05 {
            get {
                return ResourceManager.GetString("StringGoodsDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string StringGoodsDetails06 {
            get {
                return ResourceManager.GetString("StringGoodsDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 販売価格.
        /// </summary>
        public static string StringGoodsDetails07 {
            get {
                return ResourceManager.GetString("StringGoodsDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 免税額.
        /// </summary>
        public static string StringGoodsDetails08 {
            get {
                return ResourceManager.GetString("StringGoodsDetails08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合計価額.
        /// </summary>
        public static string StringGoodsDetails09 {
            get {
                return ResourceManager.GetString("StringGoodsDetails09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返金額.
        /// </summary>
        public static string StringGoodsDetails10 {
            get {
                return ResourceManager.GetString("StringGoodsDetails10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総合計価額.
        /// </summary>
        public static string StringGoodsDetails11 {
            get {
                return ResourceManager.GetString("StringGoodsDetails11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総返金額.
        /// </summary>
        public static string StringGoodsDetails12 {
            get {
                return ResourceManager.GetString("StringGoodsDetails12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総手数料.
        /// </summary>
        public static string StringGoodsDetails13 {
            get {
                return ResourceManager.GetString("StringGoodsDetails13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 総免税額.
        /// </summary>
        public static string StringGoodsDetails14 {
            get {
                return ResourceManager.GetString("StringGoodsDetails14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全店合計消耗品販売額.
        /// </summary>
        public static string StringGoodsDetails15 {
            get {
                return ResourceManager.GetString("StringGoodsDetails15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全店合計一般物品販売額.
        /// </summary>
        public static string StringGoodsDetails16 {
            get {
                return ResourceManager.GetString("StringGoodsDetails16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 稚内港フェリーターミナル.
        /// </summary>
        public static string StringLandingPort01 {
            get {
                return ResourceManager.GetString("StringLandingPort01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 神戸ポートターミナル.
        /// </summary>
        public static string StringLandingPort02 {
            get {
                return ResourceManager.GetString("StringLandingPort02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大阪国際フェリーターミナル.
        /// </summary>
        public static string StringLandingPort03 {
            get {
                return ResourceManager.GetString("StringLandingPort03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下関港国際ターミナル.
        /// </summary>
        public static string StringLandingPort04 {
            get {
                return ResourceManager.GetString("StringLandingPort04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 博多港国際ターミナル.
        /// </summary>
        public static string StringLandingPort05 {
            get {
                return ResourceManager.GetString("StringLandingPort05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 比田勝港国際ターミナル.
        /// </summary>
        public static string StringLandingPort06 {
            get {
                return ResourceManager.GetString("StringLandingPort06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旭川空港.
        /// </summary>
        public static string StringLandingPort07 {
            get {
                return ResourceManager.GetString("StringLandingPort07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 函館空港.
        /// </summary>
        public static string StringLandingPort08 {
            get {
                return ResourceManager.GetString("StringLandingPort08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新千歳空港.
        /// </summary>
        public static string StringLandingPort09 {
            get {
                return ResourceManager.GetString("StringLandingPort09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青森空港.
        /// </summary>
        public static string StringLandingPort10 {
            get {
                return ResourceManager.GetString("StringLandingPort10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秋田空港.
        /// </summary>
        public static string StringLandingPort11 {
            get {
                return ResourceManager.GetString("StringLandingPort11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仙台空港.
        /// </summary>
        public static string StringLandingPort12 {
            get {
                return ResourceManager.GetString("StringLandingPort12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 福島空港.
        /// </summary>
        public static string StringLandingPort13 {
            get {
                return ResourceManager.GetString("StringLandingPort13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 茨城空港.
        /// </summary>
        public static string StringLandingPort14 {
            get {
                return ResourceManager.GetString("StringLandingPort14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成田国際空港.
        /// </summary>
        public static string StringLandingPort15 {
            get {
                return ResourceManager.GetString("StringLandingPort15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 羽田空港.
        /// </summary>
        public static string StringLandingPort16 {
            get {
                return ResourceManager.GetString("StringLandingPort16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新潟空港.
        /// </summary>
        public static string StringLandingPort17 {
            get {
                return ResourceManager.GetString("StringLandingPort17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 富山空港.
        /// </summary>
        public static string StringLandingPort18 {
            get {
                return ResourceManager.GetString("StringLandingPort18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小松空港.
        /// </summary>
        public static string StringLandingPort19 {
            get {
                return ResourceManager.GetString("StringLandingPort19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中部国際空港.
        /// </summary>
        public static string StringLandingPort20 {
            get {
                return ResourceManager.GetString("StringLandingPort20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 富士山静岡空港.
        /// </summary>
        public static string StringLandingPort21 {
            get {
                return ResourceManager.GetString("StringLandingPort21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大阪国際空港.
        /// </summary>
        public static string StringLandingPort22 {
            get {
                return ResourceManager.GetString("StringLandingPort22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 関西国際空港.
        /// </summary>
        public static string StringLandingPort23 {
            get {
                return ResourceManager.GetString("StringLandingPort23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 米子空港.
        /// </summary>
        public static string StringLandingPort24 {
            get {
                return ResourceManager.GetString("StringLandingPort24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 岡山空港.
        /// </summary>
        public static string StringLandingPort25 {
            get {
                return ResourceManager.GetString("StringLandingPort25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 広島空港.
        /// </summary>
        public static string StringLandingPort26 {
            get {
                return ResourceManager.GetString("StringLandingPort26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 北九州空港.
        /// </summary>
        public static string StringLandingPort27 {
            get {
                return ResourceManager.GetString("StringLandingPort27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 福岡空港.
        /// </summary>
        public static string StringLandingPort28 {
            get {
                return ResourceManager.GetString("StringLandingPort28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 佐賀空港.
        /// </summary>
        public static string StringLandingPort29 {
            get {
                return ResourceManager.GetString("StringLandingPort29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 熊本空港.
        /// </summary>
        public static string StringLandingPort30 {
            get {
                return ResourceManager.GetString("StringLandingPort30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大分空港.
        /// </summary>
        public static string StringLandingPort31 {
            get {
                return ResourceManager.GetString("StringLandingPort31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宮崎空港.
        /// </summary>
        public static string StringLandingPort32 {
            get {
                return ResourceManager.GetString("StringLandingPort32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 長崎空港.
        /// </summary>
        public static string StringLandingPort33 {
            get {
                return ResourceManager.GetString("StringLandingPort33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鹿児島空港.
        /// </summary>
        public static string StringLandingPort34 {
            get {
                return ResourceManager.GetString("StringLandingPort34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 那覇空港.
        /// </summary>
        public static string StringLandingPort35 {
            get {
                return ResourceManager.GetString("StringLandingPort35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------------------------------------.
        /// </summary>
        public static string StringLine {
            get {
                return ResourceManager.GetString("StringLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運営会社.
        /// </summary>
        public static string StringOperationName {
            get {
                return ResourceManager.GetString("StringOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旅券.
        /// </summary>
        public static string StringPassPortEtc01 {
            get {
                return ResourceManager.GetString("StringPassPortEtc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旅券.
        /// </summary>
        public static string StringPassportEtc011 {
            get {
                return ResourceManager.GetString("StringPassportEtc011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外交官.
        /// </summary>
        public static string StringPassPortEtc02 {
            get {
                return ResourceManager.GetString("StringPassPortEtc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外交官.
        /// </summary>
        public static string StringPassportEtc021 {
            get {
                return ResourceManager.GetString("StringPassportEtc021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗組員上陸許可書.
        /// </summary>
        public static string StringPassPortEtc03 {
            get {
                return ResourceManager.GetString("StringPassPortEtc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乗員上陸許可書.
        /// </summary>
        public static string StringPassportEtc031 {
            get {
                return ResourceManager.GetString("StringPassportEtc031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 緊急上陸許可書.
        /// </summary>
        public static string StringPassPortEtc04 {
            get {
                return ResourceManager.GetString("StringPassPortEtc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 緊急上陸許可書.
        /// </summary>
        public static string StringPassportEtc041 {
            get {
                return ResourceManager.GetString("StringPassportEtc041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遭難上陸許可書.
        /// </summary>
        public static string StringPassPortEtc05 {
            get {
                return ResourceManager.GetString("StringPassPortEtc05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 船舶観光上陸許可書.
        /// </summary>
        public static string StringPassportEtc051 {
            get {
                return ResourceManager.GetString("StringPassportEtc051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遭難による上陸許可書.
        /// </summary>
        public static string StringPassportEtc061 {
            get {
                return ResourceManager.GetString("StringPassportEtc061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique ID.
        /// </summary>
        public static string StringRefundSerial {
            get {
                return ResourceManager.GetString("StringRefundSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFUND DETAIL.
        /// </summary>
        public static string StringRefundway {
            get {
                return ResourceManager.GetString("StringRefundway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 還付方法.
        /// </summary>
        public static string StringRefundWayDesc {
            get {
                return ResourceManager.GetString("StringRefundWayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 還付方法.
        /// </summary>
        public static string StringRefundWayName {
            get {
                return ResourceManager.GetString("StringRefundWayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / QQID .
        /// </summary>
        public static string StringRefundWayQQ {
            get {
                return ResourceManager.GetString("StringRefundWayQQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / UPI No. .
        /// </summary>
        public static string StringRefundWayUPI {
            get {
                return ResourceManager.GetString("StringRefundWayUPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 再発行.
        /// </summary>
        public static string StringRePublish {
            get {
                return ResourceManager.GetString("StringRePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 短期滞在.
        /// </summary>
        public static string StringResidence01 {
            get {
                return ResourceManager.GetString("StringResidence01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公用.
        /// </summary>
        public static string StringResidence02 {
            get {
                return ResourceManager.GetString("StringResidence02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教授.
        /// </summary>
        public static string StringResidence03 {
            get {
                return ResourceManager.GetString("StringResidence03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 芸術.
        /// </summary>
        public static string StringResidence04 {
            get {
                return ResourceManager.GetString("StringResidence04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 宗教.
        /// </summary>
        public static string StringResidence05 {
            get {
                return ResourceManager.GetString("StringResidence05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 報道.
        /// </summary>
        public static string StringResidence06 {
            get {
                return ResourceManager.GetString("StringResidence06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 投資・経営.
        /// </summary>
        public static string StringResidence07 {
            get {
                return ResourceManager.GetString("StringResidence07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 法律・会計業務.
        /// </summary>
        public static string StringResidence08 {
            get {
                return ResourceManager.GetString("StringResidence08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 医療.
        /// </summary>
        public static string StringResidence09 {
            get {
                return ResourceManager.GetString("StringResidence09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 研究.
        /// </summary>
        public static string StringResidence10 {
            get {
                return ResourceManager.GetString("StringResidence10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 教育.
        /// </summary>
        public static string StringResidence11 {
            get {
                return ResourceManager.GetString("StringResidence11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技術.
        /// </summary>
        public static string StringResidence12 {
            get {
                return ResourceManager.GetString("StringResidence12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人文知識・国際業務.
        /// </summary>
        public static string StringResidence13 {
            get {
                return ResourceManager.GetString("StringResidence13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企業内転勤.
        /// </summary>
        public static string StringResidence14 {
            get {
                return ResourceManager.GetString("StringResidence14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 興行.
        /// </summary>
        public static string StringResidence15 {
            get {
                return ResourceManager.GetString("StringResidence15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能.
        /// </summary>
        public static string StringResidence16 {
            get {
                return ResourceManager.GetString("StringResidence16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能実習.
        /// </summary>
        public static string StringResidence17 {
            get {
                return ResourceManager.GetString("StringResidence17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文化活動.
        /// </summary>
        public static string StringResidence18 {
            get {
                return ResourceManager.GetString("StringResidence18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外交.
        /// </summary>
        public static string StringResidence19 {
            get {
                return ResourceManager.GetString("StringResidence19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留学.
        /// </summary>
        public static string StringResidence20 {
            get {
                return ResourceManager.GetString("StringResidence20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 研修.
        /// </summary>
        public static string StringResidence21 {
            get {
                return ResourceManager.GetString("StringResidence21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 家族滞在.
        /// </summary>
        public static string StringResidence22 {
            get {
                return ResourceManager.GetString("StringResidence22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特定活動.
        /// </summary>
        public static string StringResidence23 {
            get {
                return ResourceManager.GetString("StringResidence23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 永住者.
        /// </summary>
        public static string StringResidence24 {
            get {
                return ResourceManager.GetString("StringResidence24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本人の配偶者等.
        /// </summary>
        public static string StringResidence25 {
            get {
                return ResourceManager.GetString("StringResidence25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 永住者の配偶者等.
        /// </summary>
        public static string StringResidence26 {
            get {
                return ResourceManager.GetString("StringResidence26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定住者.
        /// </summary>
        public static string StringResidence27 {
            get {
                return ResourceManager.GetString("StringResidence27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETAILER.
        /// </summary>
        public static string StringRetailer {
            get {
                return ResourceManager.GetString("StringRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所轄税務署.
        /// </summary>
        public static string StringRetailer01 {
            get {
                return ResourceManager.GetString("StringRetailer01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納税地.
        /// </summary>
        public static string StringRetailer02 {
            get {
                return ResourceManager.GetString("StringRetailer02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 販売者氏名・名称.
        /// </summary>
        public static string StringRetailer03 {
            get {
                return ResourceManager.GetString("StringRetailer03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 販売場所在地.
        /// </summary>
        public static string StringRetailer04 {
            get {
                return ResourceManager.GetString("StringRetailer04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伝票番号.
        /// </summary>
        public static string StringSlipNo {
            get {
                return ResourceManager.GetString("StringSlipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸出免税物品購入記録票.
        /// </summary>
        public static string StringSlipType01 {
            get {
                return ResourceManager.GetString("StringSlipType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスポート添付用.
        /// </summary>
        public static string StringSlipType01AddText01 {
            get {
                return ResourceManager.GetString("StringSlipType01AddText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ① 本邦から出国する際又は居住者となる際に、その出港地を所轄する税関長又はその住所若しくは居所の所在地を所轄する税務署長に購入記録票を提出しなければなりません。.
        /// </summary>
        public static string StringSlipType01Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ② 本邦から出国するまでは購入記録票を旅券等から切り離してはいけません。.
        /// </summary>
        public static string StringSlipType01Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ③ 免税で購入した物品を本邦からの出国の際に所持していなかった場合には、その購入した物品について免除された消費税額（地方消費税を含む。）に相当する額を徴収されます。.
        /// </summary>
        public static string StringSlipType01Desc03 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ④ ③の場合において、災害その他やむを得ない事情により免税で購入した物品を亡失したため輸出しないことにつき税関長の承認を受けたとき、又は既に輸出したことを証する書類を出港地を所轄する税関長に提出したときは、消費税額（地方消費税を含む。）に相当する額を徴収されません。.
        /// </summary>
        public static string StringSlipType01Desc04 {
            get {
                return ResourceManager.GetString("StringSlipType01Desc04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最終的に輸出となる物品の
        ///消費税免税購入についての購入者誓約書.
        /// </summary>
        public static string StringSlipType02 {
            get {
                return ResourceManager.GetString("StringSlipType02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 店舗控用.
        /// </summary>
        public static string StringSlipType02AddText01 {
            get {
                return ResourceManager.GetString("StringSlipType02AddText01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当該消耗品を、購入した日から３０日以内に輸出されるものとして購入し、日本で処分しないことを誓約します。.
        /// </summary>
        public static string StringSlipType02Desc01 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当該一般物品を、日本から最終的には輸出されるものとして購入し、日本で処分しないことを誓約します。.
        /// </summary>
        public static string StringSlipType02Desc02 {
            get {
                return ResourceManager.GetString("StringSlipType02Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 署名　Signature.
        /// </summary>
        public static string StringSlipType02Signature {
            get {
                return ResourceManager.GetString("StringSlipType02Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸出免税物品購入記録票(控え).
        /// </summary>
        public static string StringSlipType03 {
            get {
                return ResourceManager.GetString("StringSlipType03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 購入者控え.
        /// </summary>
        public static string StringSlipType04 {
            get {
                return ResourceManager.GetString("StringSlipType04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸出免税物品販売者控え.
        /// </summary>
        public static string StringSlipType05 {
            get {
                return ResourceManager.GetString("StringSlipType05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合算発行伝票.
        /// </summary>
        public static string StringSlipType06 {
            get {
                return ResourceManager.GetString("StringSlipType06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合算伝票番号.
        /// </summary>
        public static string StringSlipType06No {
            get {
                return ResourceManager.GetString("StringSlipType06No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOURIST&apos;S DETAILS.
        /// </summary>
        public static string StringTouristDetails {
            get {
                return ResourceManager.GetString("StringTouristDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旅券等の種類.
        /// </summary>
        public static string StringTouristDetails01 {
            get {
                return ResourceManager.GetString("StringTouristDetails01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 番号.
        /// </summary>
        public static string StringTouristDetails02 {
            get {
                return ResourceManager.GetString("StringTouristDetails02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 購入者氏名.
        /// </summary>
        public static string StringTouristDetails03 {
            get {
                return ResourceManager.GetString("StringTouristDetails03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 国籍.
        /// </summary>
        public static string StringTouristDetails04 {
            get {
                return ResourceManager.GetString("StringTouristDetails04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生年月日.
        /// </summary>
        public static string StringTouristDetails05 {
            get {
                return ResourceManager.GetString("StringTouristDetails05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在留資格.
        /// </summary>
        public static string StringTouristDetails06 {
            get {
                return ResourceManager.GetString("StringTouristDetails06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上陸地.
        /// </summary>
        public static string StringTouristDetails07 {
            get {
                return ResourceManager.GetString("StringTouristDetails07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上陸年月日.
        /// </summary>
        public static string StringTouristDetails08 {
            get {
                return ResourceManager.GetString("StringTouristDetails08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap trash4 {
            get {
                object obj = ResourceManager.GetObject("trash4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
